#!/bin/bash
vmhost=${VMHOST:-abeast1-sesa.bu.edu}
if [[ $vmhost != $(hostname) ]]; then
    pre="ssh -x $vmhost"
    pretty="ssh -x -t $vmhost"
else
    unset pre
    unset pretty
fi
arch=${VMARCH:-$($pre uname -i)}
base=${VMBASEVM:-basevm-$arch}

VIRSH="$PRECMD virsh"

name=$1



if [[ -z $name ]]; then
    echo "USAGE: $0 <name> [extra xml virsh network options" >> /dev/stderr
    echo "Existing networks:" >> /dev/stderr
    $VIRSH net-list --all  >> /dev/stderr
    exit -1
fi
options="<bridge name=\"${name}-br\" macTableManager=\"libvirt\"/>"

shift
options="${options}$*"
echo "<network><name>$name</name>$options</network>" | $VIRSH net-define /dev/stdin


