#!/bin/bash
#set -x
scriptdir=$(dirname $(realpath $0))
configdir=$scriptdir/config


[[ -z $VMARCH ]] && [[ -a $configdir/VMARCH ]] \
    && VMARCH=$(cat $configdir/VMARCH)
[[ -z $VMHOST ]] && [[ -a $configdir/${VMARCH}.host ]] \
    && VMHOST=$(cat $configdir/${VMARCH}.host)
vmhost=${VMHOST}

if [[ $vmhost != $(hostname) ]]; then
    pre="ssh -x $vmhost"
    pretty="ssh -x -t $vmhost"
else
    unset pre
    unset pretty
fi
arch=${VMARCH:-$($pre uname -i)}
base=${VMBASEVM:-basevm-$arch}

domain=$1

[[ -z $domain ]] && echo "USAGE: $0 <newvmname>" && exit -1


$pre virt-clone --original $base --name $domain  --auto-clone

