#!/bin/bash
#set -x
vmhost=${VMHOST:-abeast1-sesa.bu.edu}
if [[ $vmhost != $(hostname) ]]; then
    pre="ssh -x $vmhost"
    pretty="ssh -x -t $vmhost"
else
    unset pre
    unset pretty
fi
arch=${VMARCH:-$($pre uname -i)}
base=${VMBASEVM:-basevm-$arch}

domain=$1

[[ -z $domain ]] && echo "USAGE: $0 <name>" && exit -1


$pre virsh destroy $domain
$pre virsh undefine --nvram $domain

